#!/usr/bin/env bash

set -e

kubectl config set-credentials ${PLUGIN_KUBERNETES_SERVICE_ACCOUNT_NAME} --token=${PLUGIN_KUBERNETES_SERVICE_ACCOUNT_TOKEN}

echo ${PLUGIN_KUBERNETES_CERT} | base64 -d > ca.crt

kubectl config set-cluster ${PLUGIN_KUBERNETES_SERVICE_ACCOUNT_NAME} --server=${PLUGIN_KUBERNETES_SERVER} --certificate-authority=ca.crt
kubectl config set-context ${PLUGIN_KUBERNETES_SERVICE_ACCOUNT_NAME} --cluster=${PLUGIN_KUBERNETES_SERVICE_ACCOUNT_NAME} --user=${PLUGIN_KUBERNETES_SERVICE_ACCOUNT_NAME}
kubectl config use-context ${PLUGIN_KUBERNETES_SERVICE_ACCOUNT_NAME}